/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Outlay;

/**
 *
 * @author Akmal
 */
public class HalamanEditKategori extends javax.swing.JFrame {

    /**
     * Creates new form HalamanEditKategori
     */
    public HalamanEditKategori() {
        initComponents();
    }
    
    private Integer id;
    
    public HalamanEditKategori(int id, String nama) {
        initComponents();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        icon_combobox.setVisible(false);
        warna_combobox.setVisible(false);
        form_nama.setText(nama);
        jPanel1.setSize(0, 0);
        menu_button2.setSize(0, 0);
        this.id = id;
    }

    private PageCtrl PC = new PageCtrl();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        form_nama = new javax.swing.JTextField();
        icon_combobox = new javax.swing.JComboBox<>();
        warna_combobox = new javax.swing.JComboBox<>();
        button_submit = new javax.swing.JButton();
        menu_button = new javax.swing.JButton();
        menu_button2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        delete_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Edit Kategori");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(118, 11, 135, 29);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 90, 50, 20);

        jLabel3.setText("Icon");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 130, 40, 20);

        jLabel4.setText("Warna");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 170, 50, 20);

        form_nama.setPreferredSize(new java.awt.Dimension(6, 20));
        getContentPane().add(form_nama);
        form_nama.setBounds(190, 90, 160, 30);

        getContentPane().add(icon_combobox);
        icon_combobox.setBounds(190, 130, 28, 20);

        getContentPane().add(warna_combobox);
        warna_combobox.setBounds(190, 170, 28, 20);

        button_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        button_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_submitMousePressed(evt);
            }
        });
        getContentPane().add(button_submit);
        button_submit.setBounds(146, 204, 83, 59);

        menu_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_buttonMousePressed(evt);
            }
        });
        getContentPane().add(menu_button);
        menu_button.setBounds(10, 11, 25, 40);

        menu_button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        menu_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_button2MousePressed(evt);
            }
        });
        getContentPane().add(menu_button2);
        menu_button2.setBounds(10, 10, 25, 40);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        delete_button.setText("Delete");
        delete_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delete_buttonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 85, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_submitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_submitMousePressed
        // TODO add your handling code here:
        String nama = form_nama.getText();
        PC.updateKategori(this, nama, id);
    }//GEN-LAST:event_button_submitMousePressed

    private void menu_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_buttonMousePressed
        // TODO add your handling code here:
        Thread th;
        th = new Thread(){
            @Override
            public void run(){
                try{
                    for(int a=0;a<=6;a++){
                        Thread.sleep(50);
                            if(a==1){
                               jPanel1.setSize(14, 140);
                               menu_button.setSize(0, 0);
                               menu_button2.setSize(25, 40);
                            }
                            if(a==2)jPanel1.setSize(28, 140);
                            if(a==3)jPanel1.setSize(42, 140);
                            if(a==4)jPanel1.setSize(56, 140);
                            if(a==5)jPanel1.setSize(70, 140);
                            if(a==6)jPanel1.setSize(85, 140);
                            
                    
                    }
                }
                catch(Exception ex){
                    System.out.println(ex);
                }
            }
        };
        th.start();
    }//GEN-LAST:event_menu_buttonMousePressed

    private void menu_button2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_button2MousePressed
        // TODO add your handling code here:
        Thread th;
        th = new Thread(){
            @Override
            public void run(){
                try{
                    for(int a=0;a<=6;a++){
                        Thread.sleep(50);
                            if(a==1){
                               jPanel1.setSize(70, 140);
                               menu_button.setSize(25, 40);
                               menu_button2.setSize(0, 0);
                            }
                            if(a==2)jPanel1.setSize(56, 140);
                            if(a==3)jPanel1.setSize(42, 140);
                            if(a==4)jPanel1.setSize(28, 140);
                            if(a==5)jPanel1.setSize(14, 140);
                            if(a==6)jPanel1.setSize(0, 140);
                            
                    
                    }
                }
                catch(Exception ex){
                    System.out.println(ex);
                }
            }
        };
        th.start();
    }//GEN-LAST:event_menu_button2MousePressed

    private void delete_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_buttonMousePressed
        // TODO add your handling code here:
        PC.deleteOnClick(this, id);
    }//GEN-LAST:event_delete_buttonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanEditKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanEditKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanEditKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanEditKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanEditKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_submit;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField form_nama;
    private javax.swing.JComboBox<String> icon_combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu_button;
    private javax.swing.JButton menu_button2;
    private javax.swing.JComboBox<String> warna_combobox;
    // End of variables declaration//GEN-END:variables
}
